name: Build Image

on: [push, workflow_dispatch]

env:
  ENDPOINT: "catoja1107/docker-gphotos-sync"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: whoan/docker-build-with-cache-action@v6
        with:
          username: "${{ secrets.DOCKERUSER }}"
          password: "${{ secrets.DOCKERPASS }}"
          image_name: "${{ env.ENDPOINT }}"
          image_tag: latest
          stages_image_name: "catoja1107/cache-gphotos-sync-latest"
